### ISSUE TITLE
org-agenda-mode-map bind not working the first time

### ISSUE THREAD

**Issue by rnadler** [kickingvegas/casual-agenda#11]
org: 9.8
transient: 0.7.5
emacs: 29.4.50
os: Ubuntu 24.04 LTS
doom configuration:

package.el:
`(package! casual-agenda)`

config.el
```
(use-package! casual-agenda
  :ensure nil
  :config
  (setq casual-agenda-use-unicode-symbols t)
  :bind (:map
         org-agenda-mode-map ("C-o" . casual-agenda-tmenu)))
```
`C-o` does not work after org agenda is first opened. Get `Buffer is read-only: #<buffer *Org Agenda*>` because `C-o` is not bound.
Run `M-x casual-agenda-tmenu` once and the menu opens. `C-o` also gets bound and works from there on out.

I have the identical configuration for `casual-dired`, and it works fine.

**Comment by kickingvegas** [comment]
@rnadler Thanks for sharing this. Can you try using the `:after` key?

```
(use-package casual-agenda
  :ensure nil
  :config
  (setq casual-agenda-use-unicode-symbols t)
  :bind (:map
         org-agenda-mode-map ("C-o" . casual-agenda-tmenu))
  :after (org-agenda))
```

Let me know how that works.

**Comment by rnadler** [comment]
@kickingvegas 
That fixed the initial `C-o` binding. Thanks!

This should probably be a separate issue, but one other strange thing is that even though `casual-agenda-use-unicode-symbols` is `t` the icons do not show up until after I open the `casual-dried` menu.

**Comment by kickingvegas** [comment]
@rnadler There is no variable called `casual-agenda-use-unicode-symbols`. There is now a global variable called `casual-lib-use-unicode` which can be set via the settings menu by checking “Use Unicode Symbols”. Note that this setting is global to all Casual packages.

Earlier version of some Casual packages had the now obsolete convention of defining per package whether is supports Unicode symbols. Perhaps you inferred this variable from that obsolete behavior?

**Comment by rnadler** [comment]
@kickingvegas Yep, copy/paste strikes again! Didn't know about the `casual-lib-use-unicode` change. All is good now. Thanks again!

**Comment by kickingvegas** [comment]
Will update documentation to reflect `:after` key.
