### ISSUE TITLE
Missing prerequisite in the readme

### ISSUE THREAD

**Issue by torusJKL** [kickingvegas/casual-agenda#16]
When installing casual-agenda I would get the following error

    Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "habit")
      require(habit)`

Requiring org-habit fixed this.
`(require 'org-habit)`

Maybe that could be added as a prerequisite to the documentation.

**Comment by kickingvegas** [comment]
Thanks for sharing this. Unfortunately I do not have enough information to reproduce what you are seeing. Are you using `use-package`? If so then please ensure that you are using the `:after` key as [described at this link](https://github.com/kickingvegas/casual-agenda?tab=readme-ov-file#install).

**Comment by torusJKL** [comment]
After removing the old code and deleting the eln-cache I can't reproduce this anymore.
Thanks.
