### ISSUE TITLE
Transient wrong-number-of-arguments error

### ISSUE THREAD

**Issue by torusJKL** [kickingvegas/casual-agenda#17]
When using "C-o" to activate casual-agenda-tmenu I get the following error:

    internal-macroexpand-for-load: Eager macro-expansion failure: (wrong-number-of-arguments #<subr transient--expand-define-args> 3)

I'm using emacs 29.3, org 9.7.11 and Transient 0.7.5.

**Comment by kickingvegas** [comment]
Thanks for sharing this. Unfortunately I do not have enough information to reproduce what you are seeing. Are you using `use-package`? If so then please ensure that you are using the `:after` key as [described at this link](https://github.com/kickingvegas/casual-agenda?tab=readme-ov-file#install).

**Comment by kickingvegas** [comment]
@torusJKL any followup?

**Comment by torusJKL** [comment]
I have deleted the old transient code and eln-cache and reinstalled.
It works now as expected.
Thanks!
